export const SAVE_FORMDATA = "SAVE_FORMDATA"
export const DELETE_ONE_ROW = "DELETE_ONE_ROW"
export const LOAD_LIST = "LOAD_LIST"
export const RENDER_LIST = "RENDER_LIST"
export const CALL_ERROR = "CALL_ERROR"